name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test

      - name: Detekt
        run: ./gradlew detekt

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment for release
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ${{ secrets.SIGNING_KEY_FILE }}

      - name: Publish to Maven Central
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_FILE: "../${{ secrets.SIGNING_KEY_FILE }}"
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
